### ISSUE TITLE
Timezone offset

### ISSUE THREAD

**Issue by tkuther** [getsentry/sentry-kubernetes#19]
I'm experimenting with this on a baremetal cluster whose nodes have a timezone configured. (UTC +1, Europe/Berlin)

The issue I'm seeing is that events get added in Sentry with a delay of that one hour (it realizes the event is an hour old, though).

Is this something that could be fixed by configuration, or is UTC a requirement for the kubernetes nodes?

**Comment by bretthoerner** [comment]
All events should be sent in UTC time so that they can then be displayed based on the user's timezone settings here: https://sentry.io/settings/account/details/

I guess if your server has its time hardcoded Europe/Berlin then the Python client may not be able to get the correct `datetime.utcnow()`? I'm not sure how that works.

**Comment by tkuther** [comment]
Fixed. The solution was to set TZ environment variable in the sentry-kubernetes container.
